apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1 
  template: 
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: petclinic
        image: sevenajay/zipkin-2.23
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: LoadBalancer
  selector:
    app: zipkin
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
